### ISSUE TITLE
Multi threaded mesh generation and ability to generate all nav meshes at once

### ISSUE THREAD

**Issue by xnuken** [awgil/ffxiv_navmesh#14]
Would it be possible to add support for multi threaded mesh generation and an option to generate a nav mesh for every zone instead of manually visiting a zone then generating it?

**Comment by awgil** [comment]
Mesh generation can be threaded, however it would increase memory footprint significantly - and this in turn increases GC pressure, causing bad performance spikes on main thread. I plan to optimize this in future and then parallelize it.

Generating all meshes for all zones is unfortunately quite tricky. There are several reasons:
1. I did not fully reverse the code that loads zones from files, it is quite complicated and large, and supports multiple features (eg nested prefabs). Duplicating it faithfully is hard, and any mistakes would cause hard to debug differences between game state and what navmesh sees (extra or missing objects). So instead I rely on game loading the level layout and resolving all prefabs, and then simply read game structures to build the mesh.
2. Level data is actually quite complicated and supports independently loaded 'layers' - eg for in-game festivals. Generating *all* permutations is not feasible (due to combinatoric explosion), so to make the mesh generation process offline, I would somehow need to find a list of possible combinations.
